name: Java CI workflow with maven

on: [push]

jobs:
	build-and-test:
		runs-on: ubuntu-latest

		steps:
			- name: Checkout
			  uses: actions/checkout@v5

			- name: Set up Java
			  uses: actions/setup-java@v4
			  with:
				  distribution: 'temurin'
				  java-version: '22'
				  cache: 'maven'

			- name: Build + Test
			  run: mvn -B clean test